#!/usr/bin/env python3

from tkinter import *
from time import sleep
from multiprocessing import Process, Manager
import threading
import sysv_ipc
import sys

key = 777

def display(key) :
    """
    Crée une fenêtre graphique pour afficher les populations.
    Ecoute sur la message queue, récupère les messages de env et affiche les populations 
    """
    textH = "Herbe :"
    textPtor = "Predators :"
    textPrey = "Preys :"

    fenetre = Tk()
    labelH = Label(fenetre, textH)
    labelPtor = Label(fenetre, textPtor)
    labelPrey = Label(fenetre, textPrey)
    labelH.pack()
    labelPtor.pack()
    labelPrey.pack()

    fenetre.mainloop()

    mq = sysv_ipc.MessageQueue(key)
    
    mess = mq.receive()
    mess_str = mess.decode()
    while mess_str != "stop,stop,stop" :
        herb, prey, predator = mess_str(',', 2)
        textH = "Herbe :" + herb
        textPrey = "Prey :" + prey 
        textPtor = "Predator :" + predator




def env(key, pop_prey, pop_predator, grass) :
    mq = sysv_ipc.MessageQueue(key)
    thread_display = threading.Thread(target=msg_display, args=(mq, pop_prey, pop_predator, grass))
    thread_display.start()
    sleep(5)
    m_stop = "stop,stop,stop"
    stop = m_stop.encode()
    mq.send(stop, type=3)
    thread_display.join()

def msg_display(mq, pop_prey, pop_predator, grass) :
    """
    Envoie périodiquement un message "herbe,prey,predator"
    """
    sleep(0.5)
    msg = str(grass) + "," + str(len(pop_prey)) + "," + str(len(pop_predator))
    msg_send = msg.encode()
    mq.send(msg_send, type = 3)


if __name__ == "__main__" :
    mq = sysv_ipc.MessageQueue(key, sysv_ipc.IPC_CREX)
    with Manager() as manager:
        pop_predator = manager.list()
        pop_prey = manager.list()
        grass = manager.Value('i', 10)

        p_env = Process(target=env, args=(key, pop_predator, pop_prey, grass))
        p_display = Process(target=display, args=(key, pop_predator, pop_prey, grass))

        p_env.start()
        p_display.start()

        p_env.join()
        p_display.join()

    
